### ISSUE TITLE
Zoom sticks on images

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#57] opened 2022-04-26 21:37 UTC
I'm running into an issue with the zoom functionality. It will stick when I'm trying to zoom in or out. I've attached a movie to explain. I'm using the scroll wheel on the external mouse for my macbook pro. 

It seems like it happens more often when it's near the border of the image, but it's not 100% consistent
https://user-images.githubusercontent.com/13770365/165396478-c48c7043-fdcf-419b-9b19-bad82cc9d55a.mov

**Comment by rj3d** [comment] 2022-04-26 22:43
Thanks for the report. The movie was very helpful.

I think I'm able to reproduce this. It seems like the zoom gets stuck if I'm moving the mouse and trying to zoom at the same time. In your movie it looks like your mouse was slightly moving while the zoom was stuck, so maybe this is what you're experiencing as well. Could you test theory and check if the zoom works as expected for you if the mouse is not being moved?

I'll create a ticket in our system to fix the zoom stuck while mouse moving issue. I'll create another one if it looks like there's an additional issue.

**Comment by ngreenwald** [comment] 2022-04-26 23:05
Yup, that was definitely the issue! Even very subtle mouse movements can trigger it.

**Comment by rj3d** [comment] 2022-04-26 23:12
Great, thanks for checking! 

I'll look into this and post back when I have a fix.

**Comment by rj3d** [comment] 2022-04-29 03:13
Fixed in the release [https://github.com/ParkerICI/mantis-viewer/releases/tag/v1.2.2-rc.1](v1.2.2-rc.1).

**Closed by rj3d** 2022-04-29 03:13 UTC
